name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Create secret file
      #   run: echo "${{ secrets.CLIENT_ENV }}" | base64 --decode > ./client/.env
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Create production build
        run: |
          npm install
          npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: protected-cf-staging
          directory: dist
          branch: main
          wranglerVersion: '3'
